--liquibase formatted sql
--changeset it-tests:001_init_test_schema

-- Schéma des tests d'intégration : miroir du schéma de production.
-- À maintenir aligné lors de toute évolution du DDL de prod
-- (financial-persistence/src/main/resources/db/changelog/DDL).

CREATE TABLE CUSTOMER (
  CUSTOMER_ID UUID NOT NULL,
  FIRST_NAME VARCHAR(100),
  LAST_NAME VARCHAR(100),
  EMAIL VARCHAR(150),
  GENDER VARCHAR(10),
  CONSTRAINT CUSTOMER_PK PRIMARY KEY(CUSTOMER_ID)
);

CREATE TABLE ACCOUNT (
  ACCOUNT_ID UUID NOT NULL,
  RIB VARCHAR(50) UNIQUE,
  BALANCE NUMERIC(20,2),
  CREATED_AT TIMESTAMP,
  STATUS VARCHAR(20),
  CUSTOMER_ID UUID,
  ACCOUNT_TYPE VARCHAR(20),
  OVER_DRAFT NUMERIC(20,2),
  INTEREST_RATE NUMERIC(5,2),
  CONSTRAINT BANK_ACCOUNT_PK PRIMARY KEY(ACCOUNT_ID),
  CONSTRAINT FK_BANK_ACCOUNT_CUSTOMER FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);
CREATE INDEX IDX_ACCOUNT_CUSTOMER ON ACCOUNT(CUSTOMER_ID);

CREATE TABLE OPERATION (
  OPERATION_ID UUID NOT NULL,
  OPERATION_NUMBER VARCHAR(50),
  OPERATION_AMOUNT NUMERIC(20,2),
  OPERATION_DATE TIMESTAMP,
  OPERATION_TYPE VARCHAR(10),
  DESCRIPTION VARCHAR(255),
  ACCOUNT_ID UUID,
  CONSTRAINT OPERATION_PK PRIMARY KEY(OPERATION_ID),
  CONSTRAINT FK_OPERATION_ACCOUNT FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);
CREATE INDEX IDX_OPERATION_ACCOUNT ON OPERATION(ACCOUNT_ID);

CREATE TABLE BANK_STATEMENT (
  ID UUID NOT NULL,
  ACCOUNT_ID UUID NOT NULL,
  PERIOD_START DATE NOT NULL,
  PERIOD_END DATE NOT NULL,
  OPENING_BALANCE NUMERIC(20,2) NOT NULL,
  CLOSING_BALANCE NUMERIC(20,2) NOT NULL,
  STATUS VARCHAR(20) NOT NULL,
  FILE_URL VARCHAR(500),
  GENERATED_AT TIMESTAMP,
  CONSTRAINT BANK_STATEMENT_PK PRIMARY KEY (ID),
  CONSTRAINT FK_BANK_STATEMENT_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);
CREATE INDEX IDX_BANK_STATEMENT_ACCOUNT ON BANK_STATEMENT(ACCOUNT_ID);
CREATE UNIQUE INDEX IDX_BANK_STATEMENT_PERIOD ON BANK_STATEMENT(ACCOUNT_ID, PERIOD_START, PERIOD_END);

CREATE TABLE STATEMENT_LINE (
  ID UUID NOT NULL,
  STATEMENT_ID UUID NOT NULL,
  OPERATION_NUMBER VARCHAR(50),
  OPERATION_DATE TIMESTAMP NOT NULL,
  LABEL VARCHAR(255) NOT NULL,
  AMOUNT NUMERIC(20,2) NOT NULL,
  OPERATION_TYPE VARCHAR(10) NOT NULL,
  RUNNING_BALANCE NUMERIC(20,2) NOT NULL,
  CONSTRAINT STATEMENT_LINE_PK PRIMARY KEY (ID),
  CONSTRAINT FK_STATEMENT_LINE_STATEMENT FOREIGN KEY (STATEMENT_ID) REFERENCES BANK_STATEMENT(ID)
);
CREATE INDEX IDX_STATEMENT_LINE_STATEMENT ON STATEMENT_LINE(STATEMENT_ID);
