spring:
  application:
    name: financial-tracking-ws

# DataSource (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5432/financial-tracking-ws-db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

# JPA / Hibernate
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

# Liquibase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: false

# Logging
logging:
  level:
    org.springframework.boot.autoconfigure.jdbc: DEBUG

# Archive service
archive:
  service:
    url: http://localhost:8085
