--liquibase formatted sql
--changeset sbarry:003_operation

-- Table operation
CREATE TABLE OPERATION (
  OPERATION_ID UUID NOT NULL,
  OPERATION_NUMBER VARCHAR(50),
  OPERATION_AMOUNT NUMERIC(20,2),
  OPERATION_DATE TIMESTAMP,
  OPERATION_TYPE VARCHAR(10),
  DESCRIPTION VARCHAR(255),
  ACCOUNT_ID UUID,
  CONSTRAINT OPERATION_PK PRIMARY KEY(OPERATION_ID),
  CONSTRAINT FK_OPERATION_ACCOUNT FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);

-- Indexes
CREATE INDEX IDX_OPERATION_ACCOUNT ON OPERATION(ACCOUNT_ID);

