--liquibase formatted sql
--changeset sbarry:001_customer

--Table Customer
CREATE TABLE CUSTOMER (
  CUSTOMER_ID UUID NOT NULL,
  FIRST_NAME VARCHAR(100),
  LAST_NAME VARCHAR(100),
  EMAIL VARCHAR(150),
  GENDER VARCHAR(10),
  CONSTRAINT CUSTOMER_PK PRIMARY KEY(CUSTOMER_ID)
);

