--liquibase formatted sql
--changeset sbarry:002_account

--Table Account (SINGLE TABLE inheritance)
CREATE TABLE ACCOUNT (
  ACCOUNT_ID UUID NOT NULL,
  RIB VARCHAR(50) UNIQUE,
  BALANCE NUMERIC(20,2),
  CREATED_AT TIMESTAMP,
  STATUS VARCHAR(20),
  CUSTOMER_ID UUID,
  ACCOUNT_TYPE VARCHAR(20),
  OVER_DRAFT NUMERIC(20,2),
  INTEREST_RATE NUMERIC(5,2),
  CONSTRAINT BANK_ACCOUNT_PK PRIMARY KEY(ACCOUNT_ID),
  CONSTRAINT FK_BANK_ACCOUNT_CUSTOMER FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

-- Indexes
CREATE INDEX IDX_ACCOUNT_CUSTOMER ON ACCOUNT(CUSTOMER_ID);
