--liquibase formatted sql
--changeset sbarry:004_bank_statement

-- Table BankStatement
CREATE TABLE BANK_STATEMENT (
  ID                UUID         NOT NULL,
  ACCOUNT_ID        UUID         NOT NULL,
  PERIOD_START      DATE         NOT NULL,
  PERIOD_END        DATE         NOT NULL,
  OPENING_BALANCE   NUMERIC(20,2) NOT NULL,
  CLOSING_BALANCE   NUMERIC(20,2) NOT NULL,
  STATUS            VARCHAR(20)  NOT NULL,
  FILE_URL          VARCHAR(500),
  GENERATED_AT      TIMESTAMP,
  CONSTRAINT BANK_STATEMENT_PK PRIMARY KEY (ID),
  CONSTRAINT FK_BANK_STATEMENT_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID)
);

-- Index for lookups by account
CREATE INDEX IDX_BANK_STATEMENT_ACCOUNT ON BANK_STATEMENT(ACCOUNT_ID);

-- Index for monthly period lookups
CREATE INDEX IDX_BANK_STATEMENT_PERIOD ON BANK_STATEMENT(ACCOUNT_ID, PERIOD_START, PERIOD_END);
